[tool.poetry]
name = "fix-xls"
version = "0.1.0"
description = "Fix .xls files for Mister Silvio"
authors = ["tapyu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
